kmeans是一种非监督算法，旨在将数据分成k个簇，使得同一个簇内的样本更加相似，不同簇的差异性更大，主要实现步骤是：
1. 初始化：先随机选择K个初始簇中心
2. 分配簇：计算每个数据点到每个簇中心的距离，并将其分配到最近的簇
3. 更新簇中心：根据每个簇中所有簇的平均位置计算簇中心
4. 重复迭代：重新分配簇和更新中心，直到收敛或者达到最大的迭代次数

In [18]:
import torch

def kmeans(data, k, num_iters=100):
    # 在数据中随机选取k个中心
    ids = torch.randint(0, data.shape[0], (k, ))
    # k个数据点
    centerids = data[ids]
    # 迭代计算每个数据点到k个数据中心的距离
    for _ in range(num_iters):
        distance = torch.cdist(data, centerids)
        # print(distance.shape)
        # 寻找每个数据点的簇心, 返回的是类别
        labels = torch.argmin(distance, dim=1)
        print(labels)
        # 分配新的数据中心  通过类别
        new_centroids = torch.stack([data[labels == i].mean(dim=0) for i in range(k)])
        print(new_centroids)
        # # 检查是否收敛
        # if torch.all(centroids == new_centroids):
        #     break
        # centroids = new_centroids
    
    # return centroids, labels
    return None, None

# 首先定义100个二维点
data = torch.randn(100, 2)
# 将数据分成k类，也就是k个簇
k = 3
centerids, labels = kmeans(data, k, 100)

tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 2, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 0])
tensor([[-0.7827, -0.9025],
        [ 0.2622,  0.2859],
        [ 0.6656,  2.0323]])
tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 2, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 1,
        1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 0])
tensor([[-0.7827, -0.9025],
        [ 0.2622,  0.2859],
        [ 0.6656,  2.0323]])
tensor([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 2, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 